services:
  - type: web
    name: all-games-into-tg-bot
    runtime: node
    plan: free
    autoDeploy: true
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        value: "8542930176"
      - key: BOT_USERNAME
        value: "@AllGamesIntoTG"